Repository MajaLinder/SEMFIRE, pull requests merged in 2022-12, with the labels that each got.

#135 #112 change the types
  src/axis.ts
  src/cumulativeLine.ts
  src/stackedBars.ts
Labels: Sprint 6

#144 Bug fixes based on bar marking support
  .DS_Store
  src/axis.ts
  src/index.ts
  src/pareto.ts
  src/settings.ts
  src/stackedBars.ts
Labels: Sprint 7

#145 Category ticks
  src/axis.ts
  src/index.ts
  src/renderer.ts
Labels: Sprint 7

#147 Fix a bug of Category ticks
  src/axis.ts
Labels: bug

#146 Add tooltip support for bars
  src/index.ts
  src/pareto.ts
  src/renderer.ts
  src/stackedBars.ts
Labels: Sprint 7

#151 #141 Mod padding
  src/axis.ts
  src/resources.ts
Labels: Sprint 7

#157 #156 bugfix on mousover selection
  src/stackedBars.ts
Labels: bug, Sprint 7

#149 Scale labels
  src/axis.ts
  src/index.ts
  src/settings.ts
Labels: Sprint 7

#155 #109 change default visibilty
  static/mod-manifest.json
Labels: Sprint 7

#158 #153 add scatter dots to the cumulative line
  src/cumulativeLine.ts
Labels: Sprint 7

#170 #102 Rectangular selection
  package-lock.json
  package.json
  src/index.ts
  src/rectangleMarking.ts
  src/settings.ts
  src/stackedBars.ts
  static/main.css
Labels: Sprint 7

#168 #161 Adjust cumulative line weight
  src/cumulativeLine.ts
Labels: Sprint 7

#171 #167 Prioritize the line under the markers
  src/cumulativeLine.ts
Labels: Sprint 7

#169 Custom tooltip
  src/index.ts
  src/pareto.ts
  src/stackedBars.ts
  static/mod-manifest.json
Labels: Sprint 7

#172 Rule 80 20
  package-lock.json
  src/axis.ts
  src/cumulativeLine.ts
  src/index.ts
  src/resources.ts
  src/stackedBars.ts
  static/icon.svg
  static/mod-manifest.json
Labels: Sprint 7

#173 Cumulative line marking
  src/cumulativeLine.ts
  src/index.ts
  src/pareto.ts
  src/rectangleMarking.ts
  src/renderer.ts
  src/stackedBars.ts
Labels: Sprint 7

#180 #177 Cumulative line markers
  src/cumulativeLine.ts
Labels: Sprint 7

#179 8020marking
  src/stackedBars.ts
Labels: Sprint 7

#181 #176 add hover border around markers
  src/cumulativeLine.ts
Labels: Sprint 7

#183 #174 implement border when hovering cutoff line
  src/cumulativeLine.ts
  src/index.ts
  src/settings.ts
  src/stackedBars.ts
Labels: Sprint 7
