Repository MajaLinder/SEMFIRE, pull requests merged in 2022-11, with the labels that each got.

#89 #88 adjust colorAxis
  src/.DS_Store
  src/index.ts
  src/renderer.ts
Labels: enhancement, Sprint 5

#91 #83 Implement bars in d3
  package-lock.json
  src/index.ts
  src/renderer.ts
  src/stackedBars.ts
  static/index.html
  static/main.css
Labels: Sprint 5

#92 #82 Settings layer
  package-lock.json
  package.json
  src/index.ts
  src/renderer.ts
  src/settings.ts
Labels: Sprint 5

#95 #65 Cumulative line refactor
  package-lock.json
  src/axis.ts
  src/cumulativeLine.ts
  src/index.ts
  src/renderer.ts
  src/stackedBars.ts
Labels: Sprint 5

#119 Use Array.map to create the positions array.
  package-lock.json
  src/cumulativeLine.ts
Labels: Sprint 6

#118 #108 Fix syntax and namings based on feedback
  src/axis.ts
  src/cumulativeLine.ts
  src/index.ts
  src/renderer.ts
  src/stackedBars.ts
Labels: Sprint 6

#120 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#121 #111 Use index for identifying stacked bar data
  src/axis.ts
  src/cumulativeLine.ts
  src/index.ts
  src/pareto.ts
Labels: Sprint 6

#127 Revert "Revert "#111 Use index for identifying stacked bar data""
  src/axis.ts
  src/cumulativeLine.ts
  src/index.ts
  src/pareto.ts
Labels: Sprint 6

#123 Adjust ticks
  src/axis.ts
  src/index.ts
  src/renderer.ts
  src/stackedBars.ts
Labels: Sprint 6

#128 #96 Fix Mod Name Typo
  static/mod-manifest.json
Labels: Sprint 6

#122 #106 Removed casting
  src/axis.ts
  src/cumulativeLine.ts
  src/index.ts
  src/pareto.ts
  src/renderer.ts
  src/settings.ts
  src/stackedBars.ts
Labels: Sprint 6

#129 Drag and drop
  static/mod-manifest.json
Labels: Sprint 6

#130 #98 Add space in axis names
  src/index.ts
  static/mod-manifest.json
Labels: Sprint 6

#131 #115 Extract data transformation to a method
  src/index.ts
Labels: Sprint 6

#132 Bar spacing
  src/axis.ts
Labels: Sprint 6

#133 #97 Visualization size
  src/axis.ts
  src/cumulativeLine.ts
  src/resources.ts
  src/stackedBars.ts
  static/main.css
Labels: Sprint 6

#134 #99 render stacked bars
  .DS_Store
  src/index.ts
  src/pareto.ts
  src/stackedBars.ts
Labels: Sprint 6
