Repository MajaLinder/SEMFIRE, pull requests merged in 2022-10, with the labels that each got.

#33 #16 Display X axis categorical values
  dist/bundle.js
  dist/main.css
  src/index.js
  src/utility/methods.js
  src/xAxis.js
  static/main.css
Labels: MVP, Sprint 2

#37 #10 Display sorted bars
  dist/bundle.js
  dist/index.html
  dist/main.css
  src/index.js
  src/stackedBars.js
  src/utility/methods.js
  static/index.html
  static/main.css
Labels: MVP, Sprint 2

#41 #39 Categorial tick styling
  dist/bundle.js
  dist/main.css
  src/utility/methods.js
Labels: Sprint 2

#53 #15 Readme File updated
  README.md
Labels: documentation

#55 #45 changing the bar corner style
  dist/main.css
  static/main.css
Labels: Sprint 3

#57 #52 Adjust axis colors
  dist/bundle.js
  dist/main.css
  src/index.js
  src/percentage.js
  src/xAxis.js
  src/yAxis.js
  static/main.css
Labels: Sprint 3

#59 #51 Screen Responsive for all screen widths
  dist/main.css
  static/main.css
Labels: Sprint 3

#60 Change tag color
  dist/bundle.js
  dist/main.css
  src/percentage.js
  src/utility/methods.js
  src/xAxis.js
  src/yAxis.js
  static/main.css
Labels: Sprint 3

#61 #44 Spacing between bars
  dist/bundle.js
  dist/main.css
  static/main.css
Labels: Sprint 3

#71 #70 fixes sorting bars bug
  src/utility/methods.js
Labels: bug

#75 #74 Add class diagram
  ClassDiagramSprint3.png
Labels: documentation, Sprint 3

#79 Change the name with Tibco requirement
  dist/mod-manifest.json
  package.json
  static/mod-manifest.json
Labels: Sprint 3

#80 Refactor naming convention
  dist/bundle.js
  dist/index.html
  dist/main.css
  dist/mod-manifest.json
  src/categoryAxis.js
  src/cumulativeLine.js
  src/index.js
  src/percentage.js
  src/stackedBars.js
  src/utility/methods.js
  src/valueAxis.js
  src/xAxis.js
  src/yAxis.js
  static/index.html
  static/main.css
  static/mod-manifest.json
Labels: Sprint 3
