Repository MajaLinder/SEMFIRE, pull requests merged in 2022-09, with the labels that each got.

#7 Create LICENSE
  LICENSE
Labels: Sprint1

#8 #1 Add gitflow to README
  README.md
Labels: documentation, Sprint1

#21 #16 Y Scale rendering
  dist/bundle.js
  dist/main.css
  src/index.js
  src/utility/methods.js
  src/yScale.js
Labels: Sprint 1

#22 #16 Yscale render improvement
  dist/bundle.js
  dist/main.css
  node_modules/ansi-styles/package.json
  node_modules/color-convert/package.json
  node_modules/color-name/package.json
  node_modules/debug/package.json
  node_modules/ms/package.json
  package-lock.json
  src/index.js
  src/utility/methods.js
  src/yScale.js
  static/main.css
Labels: enhancement, Sprint 1

#29 #15 Update README.md
  Pareto_Chart_Prototype.png
  README.md
Labels: documentation

#30 #15 Update README.md
  README.md
Labels: documentation
